openapi: 3.0.3
info:
  title: API Калькулятор расчета стоимости доставки
  version: 1.0.0
  description: | 
   *Калькулятор расчета стоимости доставки* - сервис расчета стоимости доставки
   ### Возможности сервиса
   - расчет стоимости доставки
   - реестр месяцев доставки
   - реестр тоннажа доставки
   - реестр типов сырья доставки
   - реестр стоимости доставки
  
   Разработчик [{Софья}]({https://gitlab-dev.efko.ru/cr_ovr_web10})
    
servers:
  - url: http://localhost:8888/latest_dz_web/calculator-yii2/web/
    
tags:
  - name: calculate
    description: Расчет стоимостей
  - name: months
    description: Реестр месяцев
  - name: tonnages
    description: Реестр тоннажей
  - name: types
    description: Реестр типов сырья
  - name: prices
    description: Реестр прайсов
paths:
  /api/v1/months:
    get:
      tags:
        - months
      summary: Получить список месяцев
      responses:
        '200':
          $ref: '#/components/responses/MonthSuccessfulResponse'
        '400':
          description: Не авторизован
    
    post:
      tags:
        - months
      summary: Добавить месяц
      requestBody:
              $ref: '#/components/requestBodies/MonthData'
      responses:
        '201':
          description: Успешное добавление
        '401':
          description: Не авторизован
          
    delete:
      tags:
        - months
      summary: Удалить месяц по имени
      parameters:
        - $ref: '#/components/parameters/MonthParameter'
      responses:
        '204':
          description: Успешное удаление
        '401':
          description: Не авторизован
          
  /api/v1/tonnages:
    get:
      tags:
        - tonnages
      summary: Получить список тоннажей
      responses:
        '200':
          $ref: '#/components/responses/TonnagesSuccessfulResponse' 
        '400':
          description: Не авторизован
    post:
      tags:
        - tonnages
      summary: Добавить тоннаж
      requestBody:
              $ref: '#/components/requestBodies/TonnageRequestBody'
      responses:
        '201':
          description: Успешное добавление
        '401':
          description: Не авторизован
          
    delete:
      tags:
        - tonnages
      summary: Удалить тоннаж по значению
      parameters:
        - $ref: '#/components/parameters/TonnageParameter'
      responses:
        '204':
          description: Успешное удаление
        '401':
          description: Не авторизован
    
  /api/v1/types:
    get:
      tags:
        - types
      summary: Получить список типов сырья
      responses:
        '200':
          $ref: '#/components/responses/TypesSuccessfulResponse' 
        '400':
          description: Не авторизован
          
    post:
      tags:
        - types
      summary: Добавить тип сырья
      requestBody:
              $ref: '#/components/requestBodies/RawTypeRequestBody'
      responses:
        '201':
          description: Успешное добавление
        '401':
          description: Не авторизован
          
    delete:
      tags:
        - types
      summary: Удалить тип сырья по значению
      parameters:
        - $ref: '#/components/parameters/RawTypeParameter'
      responses:
        '204':
          description: Успешное удаление
        '401':
          description: Не авторизован
      
  /api/v1/calculate:
    get:
      tags:
        - calculate
      summary: Рассчитать цену
      parameters: 
        - $ref: '#/components/parameters/MonthParameter'
        - $ref: '#/components/parameters/RawTypeParameter'
        - $ref: '#/components/parameters/TonnageParameter'
      responses:
        '200':
          $ref: '#/components/responses/SuccessfulCalculationResponse'
        '401':
          description: Не авторизован
          
  /api/v1/prices:
    post:
      tags:
        - prices
      summary: Добавить цену
      requestBody:
        $ref: '#/components/requestBodies/PriceRequestBody'
      responses:
        '201':
          description: Успешное добавление
        '401':
          description: Не авторизован
          
    put:
      tags:
        - prices
      summary: Обновить цену
      requestBody:
        $ref: '#/components/requestBodies/PriceRequestBody'
      responses:
        '201':
          description: Успешное обновление
        '401':
          description: Не авторизован
  
components:

  requestBodies:
    MonthData:
      description: Данные месяца для добавления
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              month:
                type: string
                example: "март"
    TonnageRequestBody:
      description: Данные тоннажа для добавления
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              tonnage:
                type: integer
                example: 100
    RawTypeRequestBody:
      description: Данные типа сырья для добавления
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              raw_type:
                type: string
                example: "шрот"
    PriceRequestBody:
      description: Данные по стоимости
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              raw_type:
                type: string
                example: "соя"
              month:
                type: string
                example: "январь"
              tonnage:
                type: integer
                example: 100
              value:
                type: integer
                example: 176
                
  responses:
    MonthSuccessfulResponse:
      description: Успешный ответ
      content:
        application/json:
          example:
            - "январь"
            - "февраль"
            - "март"
    TonnagesSuccessfulResponse:
      description: Успешный ответ
      content:
        application/json:
          example:
            - 25
            - 50
            - 75
            - 100
    TypesSuccessfulResponse:
      description: Успешный ответ
      content:
        application/json:
          example:
            - "жмых"
            - "соя"
            - "шрот"
    SuccessfulCalculationResponse:
      description: Успешный ответ
      content:
        application/json:
          example:
            price: 100
            price_list:
              "жмых": 
                "январь":
                  25: 100
                  50: 145
                  75: 162
                  100: 176
                  
  parameters:
    MonthParameter:
      name: month
      in: query
      required: true
      schema:
        type: string
        example: "январь"
    TonnageParameter:
      name: tonnage
      in: query
      required: true
      schema:
        type: string
        example: 50
    RawTypeParameter:
      name: type
      in: query
      required: true
      schema:
        type: string
        example: "шрот"